<html><!-- Mirrored from php.net/manual/en/language.exceptions.php by HTTrack Website Copier/3.x [XR&CO'2013], Thu, 28 Aug 2014 15:20:46 GMT --><!-- Added by HTTrack --><head><meta http-equiv="content-type" content="text/html;charset=utf-8"><!-- /Added by HTTrack -->


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

  <title>Exceptions</title>

 <link rel="shortcut icon" href="../../favicon.ico">
 <link rel="search" type="application/opensearchdescription+xml" href="http://php.net/phpnetimprovedsearch.src" title="Add PHP.net search">
 <link rel="alternate" type="application/atom+xml" href="http://php.net/releases/feed.php" title="PHP Release feed">
 <link rel="alternate" type="application/atom+xml" href="http://php.net/feed.atom" title="PHP: Hypertext Preprocessor">

 <link rel="canonical" href="language.exceptions.html">
 <link rel="shorturl" href="http://php.net/exceptions">
 <link rel="alternate" href="http://php.net/exceptions" hreflang="x-default">

 <link rel="contents" href="index-2.html">
 <link rel="index" href="langref.html">
 <link rel="prev" href="language.namespaces.faq.html">
 <link rel="next" href="language.exceptions.extending.html">

 <link rel="alternate" href="language.exceptions.html" hreflang="en">
 <link rel="alternate" href="http://php.net/manual/pt_BR/language.exceptions.php" hreflang="pt_BR">
 <link rel="alternate" href="http://php.net/manual/zh/language.exceptions.php" hreflang="zh">
 <link rel="alternate" href="http://php.net/manual/fr/language.exceptions.php" hreflang="fr">
 <link rel="alternate" href="http://php.net/manual/de/language.exceptions.php" hreflang="de">
 <link rel="alternate" href="http://php.net/manual/it/language.exceptions.php" hreflang="it">
 <link rel="alternate" href="http://php.net/manual/ja/language.exceptions.php" hreflang="ja">
 <link rel="alternate" href="http://php.net/manual/ro/language.exceptions.php" hreflang="ro">
 <link rel="alternate" href="http://php.net/manual/ru/language.exceptions.php" hreflang="ru">
 <link rel="alternate" href="http://php.net/manual/es/language.exceptions.php" hreflang="es">
 <link rel="alternate" href="http://php.net/manual/tr/language.exceptions.php" hreflang="tr">

<link rel="stylesheet" type="text/css" href="../../cached8fe1.css?t=1401250819&amp;f=/fonts/Fira/fira.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cached4b8d.css?t=1404368420&amp;f=/fonts/Font-Awesome/css/fontello.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cached5065.css?t=1403329232&amp;f=/styles/theme-base.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cachedc78d.css?t=1401249623&amp;f=/styles/theme-medium.css" media="screen">

 <!--[if lte IE 7]>
 <link rel="stylesheet" type="text/css" href="http://php.net/styles/workarounds.ie7.css" media="screen">
 <![endif]-->

 <!--[if lte IE 8]>
 <script type="text/javascript">
  window.brokenIE = true;
 </script>
 <![endif]-->

 <!--[if lte IE 9]>
 <link rel="stylesheet" type="text/css" href="http://php.net/styles/workarounds.ie9.css" media="screen">
 <![endif]-->

 <!--[if IE]>
 <script type="text/javascript" src="http://php.net/js/ext/html5.js"></script>
 <![endif]-->

 <base>

</head>
<body class="docs " style="">


<div class="headsup"><a href="http://php.net/index.php#id2014-08-28-1">PHP 5.6.0 released</a></div>
<nav id="trick"><div><dl>
<dt><a href="getting-started.html">Getting Started</a></dt>
	<dd><a href="introduction.html">Introduction</a></dd>
	<dd><a href="tutorial.html">A simple tutorial</a></dd>
<dt><a href="langref.html">Language Reference</a></dt>
	<dd><a href="language.basic-syntax.html">Basic syntax</a></dd>
	<dd><a href="language.types.html">Types</a></dd>
	<dd><a href="language.variables.html">Variables</a></dd>
	<dd><a href="language.constants.html">Constants</a></dd>
	<dd><a href="language.expressions.html">Expressions</a></dd>
	<dd><a href="language.operators.html">Operators</a></dd>
	<dd><a href="language.control-structures.html">Control Structures</a></dd>
	<dd><a href="language.functions.html">Functions</a></dd>
	<dd><a href="language.oop5.html">Classes and Objects</a></dd>
	<dd><a href="language.namespaces.html">Namespaces</a></dd>
	<dd><a href="language.exceptions.html">Exceptions</a></dd>
	<dd><a href="language.generators.html">Generators</a></dd>
	<dd><a href="language.references.html">References Explained</a></dd>
	<dd><a href="reserved.variables.html">Predefined Variables</a></dd>
	<dd><a href="reserved.exceptions.html">Predefined Exceptions</a></dd>
	<dd><a href="reserved.interfaces.html">Predefined Interfaces and Classes</a></dd>
	<dd><a href="context.html">Context options and parameters</a></dd>
	<dd><a href="wrappers.html">Supported Protocols and Wrappers</a></dd>
</dl>
<dl>
<dt><a href="security.html">Security</a></dt>
	<dd><a href="security.intro.html">Introduction</a></dd>
	<dd><a href="security.general.html">General considerations</a></dd>
	<dd><a href="security.cgi-bin.html">Installed as CGI binary</a></dd>
	<dd><a href="security.apache.html">Installed as an Apache module</a></dd>
	<dd><a href="security.filesystem.html">Filesystem Security</a></dd>
	<dd><a href="security.database.html">Database Security</a></dd>
	<dd><a href="security.errors.html">Error Reporting</a></dd>
	<dd><a href="security.globals.html">Using Register Globals</a></dd>
	<dd><a href="security.variables.html">User Submitted Data</a></dd>
	<dd><a href="security.magicquotes.html">Magic Quotes</a></dd>
	<dd><a href="security.hiding.html">Hiding PHP</a></dd>
	<dd><a href="security.current.html">Keeping Current</a></dd>
<dt><a href="features.html">Features</a></dt>
	<dd><a href="features.http-auth.html">HTTP authentication with PHP</a></dd>
	<dd><a href="features.cookies.html">Cookies</a></dd>
	<dd><a href="features.sessions.html">Sessions</a></dd>
	<dd><a href="features.xforms.html">Dealing with XForms</a></dd>
	<dd><a href="features.file-upload.html">Handling file uploads</a></dd>
	<dd><a href="features.remote-files.html">Using remote files</a></dd>
	<dd><a href="features.connection-handling.html">Connection handling</a></dd>
	<dd><a href="features.persistent-connections.html">Persistent Database Connections</a></dd>
	<dd><a href="features.safe-mode.html">Safe Mode</a></dd>
	<dd><a href="features.commandline.html">Command line usage</a></dd>
	<dd><a href="features.gc.html">Garbage Collection</a></dd>
	<dd><a href="features.dtrace.html">DTrace Dynamic Tracing</a></dd>
</dl>
<dl>
<dt><a href="funcref.html">Function Reference</a></dt>
	<dd><a href="refs.basic.php.html">Affecting PHP's Behaviour</a></dd>
	<dd><a href="refs.utilspec.audio.html">Audio Formats Manipulation</a></dd>
	<dd><a href="refs.remote.auth.html">Authentication Services</a></dd>
	<dd><a href="refs.utilspec.cmdline.html">Command Line Specific Extensions</a></dd>
	<dd><a href="refs.compression.html">Compression and Archive Extensions</a></dd>
	<dd><a href="refs.creditcard.html">Credit Card Processing</a></dd>
	<dd><a href="refs.crypto.html">Cryptography Extensions</a></dd>
	<dd><a href="refs.database.html">Database Extensions</a></dd>
	<dd><a href="refs.calendar.html">Date and Time Related Extensions</a></dd>
	<dd><a href="refs.fileprocess.file.html">File System Related Extensions</a></dd>
	<dd><a href="refs.international.html">Human Language and Character Encoding Support</a></dd>
	<dd><a href="refs.utilspec.image.html">Image Processing and Generation</a></dd>
	<dd><a href="refs.remote.mail.html">Mail Related Extensions</a></dd>
	<dd><a href="refs.math.html">Mathematical Extensions</a></dd>
	<dd><a href="refs.utilspec.nontext.html">Non-Text MIME Output</a></dd>
	<dd><a href="refs.fileprocess.process.html">Process Control Extensions</a></dd>
	<dd><a href="refs.basic.other.html">Other Basic Extensions</a></dd>
	<dd><a href="refs.remote.other.html">Other Services</a></dd>
	<dd><a href="refs.search.html">Search Engine Extensions</a></dd>
	<dd><a href="refs.utilspec.server.html">Server Specific Extensions</a></dd>
	<dd><a href="refs.basic.session.html">Session Extensions</a></dd>
	<dd><a href="refs.basic.text.html">Text Processing</a></dd>
	<dd><a href="refs.basic.vartype.html">Variable and Type Related Extensions</a></dd>
	<dd><a href="refs.webservice.html">Web Services</a></dd>
	<dd><a href="refs.utilspec.windows.html">Windows Only Extensions</a></dd>
	<dd><a href="refs.xml.html">XML Manipulation</a></dd>
</dl>
<dl>
<dt>Keyboard Shortcuts</dt><dt>?</dt>
<dd>This help</dd>
<dt>j</dt>
<dd>Next menu item</dd>
<dt>k</dt>
<dd>Previous menu item</dd>
<dt>g p</dt>
<dd>Previous man page</dd>
<dt>g n</dt>
<dd>Next man page</dd>
<dt>G</dt>
<dd>Scroll to bottom</dd>
<dt>g g</dt>
<dd>Scroll to top</dd>
<dt>g h</dt>
<dd>Goto homepage</dd>
<dt>g s</dt>
<dd>Goto search<br>(current page)</dd>
<dt>/</dt>
<dd>Focus search box</dd>
</dl></div></nav>
<div id="goto">
    <div class="search">
         <div class="text"></div>
         <div class="results"><ul></ul></div>
   </div>
</div>

  <div id="breadcrumbs" class="row-fluid">
          
              
        <ul class="breadcrumbs-container">
            <li><a href="index-2.html">PHP Manual</a></li>      <li><a href="langref.html">Language Reference</a></li>    </ul>
  </div>




<div id="layout">
  <section id="layout-content">
  <div id="language.exceptions" class="chapter">
  <h1>Exceptions</h1>
<h2>Table of Contents</h2><ul class="chunklist chunklist_chapter"><li><a href="language.exceptions.extending.html">Extending Exceptions</a></li></ul>


  <p class="para">
   PHP 5 has an exception model similar to that of other programming languages.
   An exception can be <em>throw</em>n, and caught
   ("<em>catch</em>ed") within PHP. Code may be surrounded in a
   <em>try</em> block, to facilitate the catching of potential
   exceptions. Each <em>try</em> must have at least one
   corresponding <em>catch</em> block. Multiple
   <em>catch</em> blocks can be used to catch different classes of
   exceptions. Normal execution (when no exception is thrown within the
   <em>try</em> block, or when a <em>catch</em> matching
   the thrown exception's class is not present) will continue after that last
   <em>catch</em> block defined in sequence. Exceptions can be
   <em>throw</em>n (or re-thrown) within a <em>catch</em> block.
  </p>
  <p class="para">
   When an exception is thrown, code following the statement will not be
   executed, and PHP will attempt to find the first matching
   <em>catch</em> block. If an
   exception is not caught, a PHP Fatal Error will be issued with an
   "<em>Uncaught Exception ...</em>" message, unless a handler has
   been defined with <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span>.
  </p>
  <p class="para">
   In PHP 5.5 and later, a <em>finally</em> block may also be
   specified after the <em>catch</em> blocks. Code within the
   <em>finally</em> block will always be executed after the
   <em>try</em> and <em>catch</em> blocks, regardless of
   whether an exception has been thrown, and before normal execution resumes.
  </p>
  <p class="para">
   The thrown object must be an instance of the <a href="class.exception.html" class="classname">Exception</a>
   class or a subclass of <a href="class.exception.html" class="classname">Exception</a>. Trying to throw an
   object that is not will result in a PHP Fatal Error.
  </p>
  <blockquote class="note"><p><strong class="note">Note</strong>: 
   </p><p class="para">
    Internal PHP functions mainly use
    <a href="errorfunc.configuration.html#ini.error-reporting" class="link">Error reporting</a>, only modern
    <a href="language.oop5.html" class="link">Object oriented</a>
    extensions use exceptions. However, errors can be simply translated to
    exceptions with <a href="class.errorexception.html" class="link">ErrorException</a>.
   </p>
  <p></p></blockquote>
  <div class="tip"><strong class="tip">Tip</strong>
   <p class="para">
    The <a href="intro.spl.html" class="link">Standard PHP Library (SPL)</a> provides a
    good number of <a href="spl.exceptions.html" class="link">built-in exceptions</a>.
   </p>
  </div>
   <div class="example" id="example-288">
    <p><strong>Example #1 Throwing an Exception</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Division&nbsp;by&nbsp;zero.'</span><span style="color: #007700">);<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br>}<br><br>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'Caught&nbsp;exception:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>}<br><br></span><span style="color: #FF8000">//&nbsp;Continue&nbsp;execution<br></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Hello&nbsp;World\n"</span><span style="color: #007700">;<br></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>The above example will output:</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>0.2
Caught exception: Division by zero.
Hello World
</pre></div>
    </div>
   </div>
   <div class="example" id="example-289">
    <p><strong>Example #2 Exception handling with a <em>finally</em> block</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Division&nbsp;by&nbsp;zero.'</span><span style="color: #007700">);<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br>}<br><br>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'Caught&nbsp;exception:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>}&nbsp;finally&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"First&nbsp;finally.\n"</span><span style="color: #007700">;<br>}<br><br>try&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'Caught&nbsp;exception:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>}&nbsp;finally&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"Second&nbsp;finally.\n"</span><span style="color: #007700">;<br>}<br><br></span><span style="color: #FF8000">//&nbsp;Continue&nbsp;execution<br></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Hello&nbsp;World\n"</span><span style="color: #007700">;<br></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>The above example will output:</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>0.2
First finally.
Caught exception: Division by zero.
Second finally.
Hello World
</pre></div>
    </div>
   </div>
   <div class="example" id="example-290">
    <p><strong>Example #3 Nested Exception</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br><br></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br><br>class&nbsp;</span><span style="color: #0000BB">Test&nbsp;</span><span style="color: #007700">{<br>&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;</span><span style="color: #0000BB">testing</span><span style="color: #007700">()&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">MyException</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo!'</span><span style="color: #007700">);<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">MyException&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;rethrow&nbsp;it<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">throw&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">());<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>}<br><br></span><span style="color: #0000BB">$foo&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br><br></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>The above example will output:</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>string(4) "foo!"
</pre></div>
    </div>
   </div>
   
  

 </div>

<section id="usernotes">
 <div class="head"><h3 class="title">User Contributed Notes</h3></div><div id="allnotes">
  <div class="note" id="103819">  
  <a class="name">
  <strong class="user"><em>Johan</em></strong></a><div class="date" title="2011-05-05 01:18"><strong>3 years ago</strong></div>
  <div class="text" id="Hcom103819">
<div class="phpcode"><code><span class="html">
Custom error handling on entire pages can avoid half rendered pages for the users:<br><br><span class="default">&lt;?php<br>ob_start</span><span class="keyword">();<br>try {<br>&nbsp; &nbsp; </span><span class="comment">/*contains all page logic <br>&nbsp; &nbsp; and throws error if needed*/<br>&nbsp; &nbsp; </span><span class="keyword">...<br>} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; </span><span class="default">ob_end_clean</span><span class="keyword">();<br>&nbsp; </span><span class="default">displayErrorPage</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br>}<br></span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="97963">  
  <a class="name">
  <strong class="user"><em>zmunoz at gmail dot com</em></strong></a><div class="date" title="2010-05-18 01:05"><strong>4 years ago</strong></div>
  <div class="text" id="Hcom97963">
<div class="phpcode"><code><span class="html">
When catching an exception inside a namespace it is important that you escape to the global space:<br><br><span class="default">&lt;?php<br> </span><span class="keyword">namespace </span><span class="default">SomeNamespace</span><span class="keyword">;<br><br> class </span><span class="default">SomeClass </span><span class="keyword">{<br><br>&nbsp; function </span><span class="default">SomeFunction</span><span class="keyword">() {<br>&nbsp;&nbsp; try {<br>&nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'Some Error Message'</span><span class="keyword">);<br>&nbsp;&nbsp; } catch (\</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; &nbsp; </span><span class="default">var_dump</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br>&nbsp;&nbsp; }<br>&nbsp; }<br><br> }<br></span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="91159">  
  <a class="name">
  <strong class="user"><em>ask at nilpo dot com</em></strong></a><div class="date" title="2009-05-27 12:19"><strong>5 years ago</strong></div>
  <div class="text" id="Hcom91159">
<div class="phpcode"><code><span class="html">
If you intend on creating a lot of custom exceptions, you may find this code useful.&nbsp; I've created an interface and an abstract exception class that ensures that all parts of the built-in Exception class are preserved in child classes.&nbsp; It also properly pushes all information back to the parent constructor ensuring that nothing is lost.&nbsp; This allows you to quickly create new exceptions on the fly.&nbsp; It also overrides the default __toString method with a more thorough one.<br><br><span class="default">&lt;?php<br></span><span class="keyword">interface </span><span class="default">IException<br></span><span class="keyword">{<br>&nbsp; &nbsp; </span><span class="comment">/* Protected methods inherited from Exception class */<br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">getMessage</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Exception message <br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">getCode</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// User-defined Exception code<br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">getFile</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source filename<br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">getLine</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source line<br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">getTrace</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// An array of the backtrace()<br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">getTraceAsString</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Formated string of trace<br>&nbsp; &nbsp; <br>&nbsp; &nbsp; /* Overrideable methods inherited from Exception class */<br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">__toString</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// formated string for display<br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">);<br>}<br><br>abstract class </span><span class="default">CustomException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">implements </span><span class="default">IException<br></span><span class="keyword">{<br>&nbsp; &nbsp; protected </span><span class="default">$message </span><span class="keyword">= </span><span class="string">'Unknown exception'</span><span class="keyword">;&nbsp; &nbsp;&nbsp; </span><span class="comment">// Exception message<br>&nbsp; &nbsp; </span><span class="keyword">private&nbsp;&nbsp; </span><span class="default">$string</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Unknown<br>&nbsp; &nbsp; </span><span class="keyword">protected </span><span class="default">$code&nbsp; &nbsp; </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// User-defined exception code<br>&nbsp; &nbsp; </span><span class="keyword">protected </span><span class="default">$file</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source filename of exception<br>&nbsp; &nbsp; </span><span class="keyword">protected </span><span class="default">$line</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source line of exception<br>&nbsp; &nbsp; </span><span class="keyword">private&nbsp;&nbsp; </span><span class="default">$trace</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Unknown<br><br>&nbsp; &nbsp; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">)<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; if (!</span><span class="default">$message</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">$this</span><span class="keyword">(</span><span class="string">'Unknown '</span><span class="keyword">. </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">));<br>&nbsp; &nbsp; &nbsp; &nbsp; }<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">parent</span><span class="keyword">::</span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">);<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; <br>&nbsp; &nbsp; public function </span><span class="default">__toString</span><span class="keyword">()<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; return </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">) . </span><span class="string">" '</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">message</span><span class="keyword">}</span><span class="string">' in </span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">file</span><span class="keyword">}</span><span class="string">(</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">line</span><span class="keyword">}</span><span class="string">)\n"<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="keyword">. </span><span class="string">"</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">()}</span><span class="string">"</span><span class="keyword">;<br>&nbsp; &nbsp; }<br>}<br></span><span class="default">?&gt;<br></span><br>Now you can create new exceptions in one line:<br><br><span class="default">&lt;?php<br></span><span class="keyword">class </span><span class="default">TestException </span><span class="keyword">extends </span><span class="default">CustomException </span><span class="keyword">{}<br></span><span class="default">?&gt;<br></span><br>Here's a test that shows that all information is properly preserved throughout the backtrace.<br><br><span class="default">&lt;?php<br></span><span class="keyword">function </span><span class="default">exceptionTest</span><span class="keyword">()<br>{<br>&nbsp; &nbsp; try {<br>&nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">TestException</span><span class="keyword">();<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; catch (</span><span class="default">TestException $e</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; echo </span><span class="string">"Caught TestException ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; echo </span><span class="string">"Caught Exception ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br>&nbsp; &nbsp; }<br>}<br><br>echo </span><span class="string">'&lt;pre&gt;' </span><span class="keyword">. </span><span class="default">exceptionTest</span><span class="keyword">() . </span><span class="string">'&lt;/pre&gt;'</span><span class="keyword">;<br></span><span class="default">?&gt;<br></span><br>Here's a sample output:<br><br>Caught TestException ('Unknown TestException')<br>TestException 'Unknown TestException' in C:\xampp\htdocs\CustomException\CustomException.php(31)<br>#0 C:\xampp\htdocs\CustomException\ExceptionTest.php(19): CustomException-&gt;__construct()<br>#1 C:\xampp\htdocs\CustomException\ExceptionTest.php(43): exceptionTest()<br>#2 {main}</span>
</code></div>
  </div>
 </div>
  <div class="note" id="114207">  
  <a class="name">
  <strong class="user"><em>php at marcuspope dot com</em></strong></a><div class="date" title="2014-01-24 05:42"><strong>7 months ago</strong></div>
  <div class="text" id="Hcom114207">
<div class="phpcode"><code><span class="html">
Using a return statement inside a finally block will override any other return statement or thrown exception from the try block and all defined catch blocks.&nbsp;&nbsp; Code execution in the parent stack will continue as if the exception was never thrown.&nbsp; <br><br>Frankly this is a good design decision because it means I can optionally dismiss all thrown exceptions from 1 or more catch blocks in one place, without having to nest my whole try block inside an additional (and otherwise needless) try/catch block.<br><br>This is the same behavior as Java, whereas C# throws a compile time error when a return statement exists inside a finally block.&nbsp; So I figured it was worth pointing out to PHP devs who may not have any exposure to finally blocks or how other languages do it.<br><br><span class="default">&lt;?php<br><br></span><span class="keyword">function </span><span class="default">asdf</span><span class="keyword">()<br>{<br>&nbsp; &nbsp; try {<br>&nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'error'</span><span class="keyword">);<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; echo </span><span class="string">"An error occurred"</span><span class="keyword">;<br>&nbsp; &nbsp; &nbsp; &nbsp; throw </span><span class="default">$e</span><span class="keyword">;<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; finally {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">//This overrides the exception as if it were never thrown<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="keyword">return </span><span class="string">"\nException erased"</span><span class="keyword">;<br>&nbsp; &nbsp; }<br>}<br><br>try {<br>&nbsp; &nbsp; echo </span><span class="default">asdf</span><span class="keyword">();<br>}<br>catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; &nbsp; echo </span><span class="string">"\nResult: " </span><span class="keyword">. </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br>}<br></span><span class="default">?&gt;<br></span><br>The output from above will look like this:<br><br>&nbsp; &nbsp; An error occurred<br>&nbsp; &nbsp; Exception erased<br><br>Without the return statement in the finally block it would look like this:<br><br>&nbsp; &nbsp; An error occurred<br>&nbsp; &nbsp; Result: error</span>
</code></div>
  </div>
 </div>
  <div class="note" id="68697">  
  <a class="name">
  <strong class="user"><em>jazfresh at hotmail.com</em></strong></a><div class="date" title="2006-08-07 10:18"><strong>8 years ago</strong></div>
  <div class="text" id="Hcom68697">
<div class="phpcode"><code><span class="html">
Sometimes you want a single catch() to catch multiple types of Exception. In a language like Python, you can specify multiple types in a catch(), but in PHP you can only specify one. This can be annoying when you want handle many different Exceptions with the same catch() block.<br><br>However, you can replicate the functionality somewhat, because catch(&lt;classname&gt; $var) will match the given &lt;classname&gt; *or any of it's sub-classes*.<br><br>For example:<br><br><span class="default">&lt;?php<br></span><span class="keyword">class </span><span class="default">DisplayException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{};<br>class </span><span class="default">FileException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{};<br>class </span><span class="default">AccessControl </span><span class="keyword">extends </span><span class="default">FileException </span><span class="keyword">{}; </span><span class="comment">// Sub-class of FileException<br></span><span class="keyword">class </span><span class="default">IOError </span><span class="keyword">extends </span><span class="default">FileException </span><span class="keyword">{}; </span><span class="comment">// Sub-class of FileException<br><br></span><span class="keyword">try {<br>&nbsp; if(!</span><span class="default">is_readable</span><span class="keyword">(</span><span class="default">$somefile</span><span class="keyword">))<br>&nbsp; &nbsp;&nbsp; throw new </span><span class="default">IOError</span><span class="keyword">(</span><span class="string">"File is not readable!"</span><span class="keyword">);<br>&nbsp; if(!</span><span class="default">user_has_access_to_file</span><span class="keyword">(</span><span class="default">$someuser</span><span class="keyword">, </span><span class="default">$somefile</span><span class="keyword">))<br>&nbsp; &nbsp;&nbsp; throw new </span><span class="default">AccessControl</span><span class="keyword">(</span><span class="string">"Permission denied!"</span><span class="keyword">);<br>&nbsp; if(!</span><span class="default">display_file</span><span class="keyword">(</span><span class="default">$somefile</span><span class="keyword">))<br>&nbsp; &nbsp;&nbsp; throw new </span><span class="default">DisplayException</span><span class="keyword">(</span><span class="string">"Couldn't display file!"</span><span class="keyword">);<br><br>} catch (</span><span class="default">FileException $e</span><span class="keyword">) {<br>&nbsp; </span><span class="comment">// This block will catch FileException, AccessControl or IOError exceptions, but not Exceptions or DisplayExceptions.<br>&nbsp; </span><span class="keyword">echo </span><span class="string">"File error: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br>&nbsp; exit(</span><span class="default">1</span><span class="keyword">);<br>}<br></span><span class="default">?&gt;<br></span><br>Corollary: If you want to catch *any* exception, no matter what the type, just use "catch(Exception $var)", because all exceptions are sub-classes of the built-in Exception.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="112507">  
  <a class="name">
  <strong class="user"><em>Edu</em></strong></a><div class="date" title="2013-06-24 06:13"><strong>1 year ago</strong></div>
  <div class="text" id="Hcom112507">
<div class="phpcode"><code><span class="html">
The "finally" block can change the exception that has been throw by the catch block.<br><br><span class="default">&lt;?php<br></span><span class="keyword">try{<br>&nbsp; &nbsp; &nbsp; &nbsp; try {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Hello"</span><span class="keyword">);<br>&nbsp; &nbsp; &nbsp; &nbsp; } catch(\</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch in\n"</span><span class="keyword">;<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw </span><span class="default">$e</span><span class="keyword">;<br>&nbsp; &nbsp; &nbsp; &nbsp; } finally {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" finally \n"</span><span class="keyword">;<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Bye"</span><span class="keyword">);<br>&nbsp; &nbsp; &nbsp; &nbsp; }<br>} catch (\</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch out\n"</span><span class="keyword">;<br>}<br></span><span class="default">?&gt;<br></span><br>The output is:<br><br>Hello catch in<br>Hello finally <br>Bye catch out</span>
</code></div>
  </div>
 </div>
  <div class="note" id="113368">  
  <a class="name">
  <strong class="user"><em>cyrus+php at boadway dot ca</em></strong></a><div class="date" title="2013-10-02 02:50"><strong>10 months ago</strong></div>
  <div class="text" id="Hcom113368">
<div class="phpcode"><code><span class="html">
There's some inconsistent behaviour associated with PHP 5.5.3's finally and return statements. If a method returns a variable in a try block (e.g. return $foo;), and finally modifies that variable, the /modified/ value is returned. However, if the try block has a return that has to be evaluated in-line (e.g. return $foo+0;), finally's changes to $foo will /not/ affect the return value.<br><br>[code]<br>function returnVariable(){<br>&nbsp; &nbsp; $foo = 1;<br>&nbsp; &nbsp; try{<br>&nbsp; &nbsp; &nbsp; &nbsp; return $foo;<br>&nbsp; &nbsp; } finally {<br>&nbsp; &nbsp; &nbsp; &nbsp; $foo++;<br>&nbsp; &nbsp; }<br>}<br><br>function returnVariablePlusZero(){<br>&nbsp; &nbsp; $foo = 1;<br>&nbsp; &nbsp; try{<br>&nbsp; &nbsp; &nbsp; &nbsp; return $foo + 0;<br>&nbsp; &nbsp; } finally {<br>&nbsp; &nbsp; &nbsp; &nbsp; $foo++;<br>&nbsp; &nbsp; }<br>}<br><br>$test1 = returnVariable(); // returns 2, not the correct value of 1.<br>$test2 = returnVariablePlusZero(); // returns correct value of 1, but inconsistent with $test1.<br>[/code]<br><br>It looks like it's trying to be efficient by not allocating additional memory for the return value when it thinks it doesn't have to, but the spec is that finally is run after try is completed execution, and that includes the evaluation of the return expression.<br><br>One could argue (weakly) that the first method should be the correct result, but at least the two methods should be consistent.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="112527">  
  <a class="name">
  <strong class="user"><em>sander at rotorsolutions dot nl</em></strong></a><div class="date" title="2013-06-26 02:05"><strong>1 year ago</strong></div>
  <div class="text" id="Hcom112527">
<div class="phpcode"><code><span class="html">
Just an example why finally blocks are usefull (5.5)<br><br><span class="default">&lt;?php<br><br></span><span class="comment">//without catch<br></span><span class="keyword">function </span><span class="default">example</span><span class="keyword">() {<br>&nbsp; try {<br>&nbsp; &nbsp; </span><span class="comment">//do something that throws an exeption<br>&nbsp; </span><span class="keyword">}<br>&nbsp; finally {<br>&nbsp; &nbsp; </span><span class="comment">//this code will be executed even when the exception is executed<br>&nbsp; </span><span class="keyword">}<br>}<br><br>function </span><span class="default">example2</span><span class="keyword">() {<br>&nbsp; try {<br>&nbsp; &nbsp;&nbsp; </span><span class="comment">//open sql connection check user as example<br>&nbsp; &nbsp;&nbsp; </span><span class="keyword">if(</span><span class="default">condition</span><span class="keyword">) { <br>&nbsp; &nbsp; &nbsp; &nbsp; return </span><span class="default">false</span><span class="keyword">;<br>&nbsp; &nbsp;&nbsp; }<br>&nbsp; }<br>&nbsp; finally {<br>&nbsp; &nbsp; </span><span class="comment">//close the sql connection, this will be executed even if the return is called.<br>&nbsp; </span><span class="keyword">}<br>}<br><br></span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="81960">  
  <a class="name">
  <strong class="user"><em>michael dot ochs at gmx dot net</em></strong></a><div class="date" title="2008-03-21 03:44"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom81960">
<div class="phpcode"><code><span class="html">
Actually it isn't possible to do:<br><span class="default">&lt;?php<br>someFunction</span><span class="keyword">() OR throw new </span><span class="default">Exception</span><span class="keyword">();<br></span><span class="default">?&gt;<br></span><br>This leads to a T_THROW Syntax Error. If you want to use this kind of exceptions, you can do the following:<br><br><span class="default">&lt;?php<br></span><span class="keyword">function </span><span class="default">throwException</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">,</span><span class="default">$code </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">) {<br>&nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">,</span><span class="default">$code</span><span class="keyword">);<br>}<br><br></span><span class="default">someFunction</span><span class="keyword">() OR </span><span class="default">throwException</span><span class="keyword">();<br></span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="112529">  
  <a class="name">
  <strong class="user"><em>sander at rotorsolutions dot nl</em></strong></a><div class="date" title="2013-06-26 02:08"><strong>1 year ago</strong></div>
  <div class="text" id="Hcom112529">
<div class="phpcode"><code><span class="html">
Just an example why finally blocks are usefull (5.5)<br><br><span class="default">&lt;?php<br><br></span><span class="comment">//without catch<br></span><span class="keyword">function </span><span class="default">example</span><span class="keyword">() {<br>&nbsp; try {<br>&nbsp; &nbsp; </span><span class="comment">//do something that throws an exeption<br>&nbsp; </span><span class="keyword">}<br>&nbsp; finally {<br>&nbsp; &nbsp; </span><span class="comment">//this code will be executed even when the exception is executed<br>&nbsp; </span><span class="keyword">}<br>}<br><br>function </span><span class="default">example2</span><span class="keyword">() {<br>&nbsp; try {<br>&nbsp; &nbsp;&nbsp; </span><span class="comment">//open sql connection check user as example<br>&nbsp; &nbsp;&nbsp; </span><span class="keyword">if(</span><span class="default">condition</span><span class="keyword">) { <br>&nbsp; &nbsp; &nbsp; &nbsp; return </span><span class="default">false</span><span class="keyword">;<br>&nbsp; &nbsp;&nbsp; }<br>&nbsp; }<br>&nbsp; finally {<br>&nbsp; &nbsp; </span><span class="comment">//close the sql connection, this will be executed even if the return is called.<br>&nbsp; </span><span class="keyword">}<br>}</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="86476">  
  <a class="name">
  <strong class="user"><em>Shot (Piotr Szotkowski)</em></strong></a><div class="date" title="2008-10-21 12:13"><strong>5 years ago</strong></div>
  <div class="text" id="Hcom86476">
<div class="phpcode"><code><span class="html">
‘Normal execution (when no exception is thrown within the try block, *or when a catch matching the thrown exception’s class is not present*) will continue after that last catch block defined in sequence.’<br><br>‘If an exception is not caught, a PHP Fatal Error will be issued with an “Uncaught Exception …” message, unless a handler has been defined with set_exception_handler().’<br><br>These two sentences seem a bit contradicting about what happens ‘when a catch matching the thrown exception’s class is not present’ (and the second sentence is actually correct).</span>
</code></div>
  </div>
 </div>
  <div class="note" id="115257">  
  <a class="name">
  <strong class="user"><em>Hayley Watson</em></strong></a><div class="date" title="2014-06-23 06:58"><strong>2 months ago</strong></div>
  <div class="text" id="Hcom115257">
<div class="phpcode"><code><span class="html">
Remember that Exceptions are also objects and can be handled as such; they can be constructed in and returned as values from functions, passed as arguments to other functions, and examined before being thrown. You don't have to throw it as soon as you have constructed it (the stack trace will of course reflect the moment the Exception was constructed, not the moment it was thrown).<br><br>You might, for example, want to collect additional information to include in YourException but you don't want to clutter up the YourException class or the code containing the "throw" statement by collecting the information there. Or you might want to do something (such as logging) with each Exception that is thrown from a certain region (catch it, pass it to the logging function, then rethrow it).</span>
</code></div>
  </div>
 </div>
  <div class="note" id="115240">  
  <a class="name">
  <strong class="user"><em>telefoontoestel at nospam dot org</em></strong></a><div class="date" title="2014-06-18 12:34"><strong>2 months ago</strong></div>
  <div class="text" id="Hcom115240">
<div class="phpcode"><code><span class="html">
When using finally keep in mind that when a exit/die statement is used in the catch block it will NOT go through the finally block. <br><br><span class="default">&lt;?php<br></span><span class="keyword">try {<br>&nbsp; &nbsp; echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br>&nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br>} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br>&nbsp; &nbsp; echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br>} finally {<br>&nbsp; &nbsp; echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br>}<br><br></span><span class="comment">// try block<br>// catch block<br>// finally block<br></span><span class="default">?&gt;<br></span><br><span class="default">&lt;?php<br></span><span class="keyword">try {<br>&nbsp; &nbsp; echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br>&nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br>} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br>&nbsp; &nbsp; echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br>&nbsp; &nbsp; exit(</span><span class="default">1</span><span class="keyword">);<br>} finally {<br>&nbsp; &nbsp; echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br>}<br><br></span><span class="comment">// try block<br>// catch block<br></span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="113328">  
  <a class="name">
  <strong class="user"><em>jim at anderos dot com</em></strong></a><div class="date" title="2013-09-27 05:22"><strong>11 months ago</strong></div>
  <div class="text" id="Hcom113328">
<div class="phpcode"><code><span class="html">
If you are using a namespace, you must indicate the global namespace when using Exceptions.<br><span class="default">&lt;?php<br></span><span class="keyword">namespace </span><span class="default">alpha</span><span class="keyword">;<br>function </span><span class="default">foo</span><span class="keyword">(){<br>&nbsp; &nbsp; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Something is wrong!"</span><span class="keyword">);<br>&nbsp; &nbsp; </span><span class="comment">// throw new Exception(""); will fail<br></span><span class="keyword">}<br><br>try {<br>&nbsp; &nbsp; </span><span class="default">foo</span><span class="keyword">();<br>} catch( \</span><span class="default">Exception $e </span><span class="keyword">) {<br>&nbsp; &nbsp; </span><span class="comment">// catch( Exception $e ) will give no warning, but will not catch Exception<br>&nbsp; &nbsp; </span><span class="keyword">echo </span><span class="string">"ERROR: </span><span class="default">$e</span><span class="string">"</span><span class="keyword">;<br>}<br><br></span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="112528">  
  <a class="name">
  <strong class="user"><em>sander at rotorsolutions dot nl</em></strong></a><div class="date" title="2013-06-26 02:06"><strong>1 year ago</strong></div>
  <div class="text" id="Hcom112528">
<div class="phpcode"><code><span class="html">
Just an example why finally blocks are usefull (5.5)<br><br><span class="default">&lt;?php<br><br></span><span class="comment">//without catch<br></span><span class="keyword">function </span><span class="default">example</span><span class="keyword">() {<br>&nbsp; try {<br>&nbsp; &nbsp; </span><span class="comment">//do something that throws an exeption<br>&nbsp; </span><span class="keyword">}<br>&nbsp; finally {<br>&nbsp; &nbsp; </span><span class="comment">//this code will be executed even when the exception is executed<br>&nbsp; </span><span class="keyword">}<br>}<br><br>function </span><span class="default">example2</span><span class="keyword">() {<br>&nbsp; try {<br>&nbsp; &nbsp;&nbsp; </span><span class="comment">//open sql connection check user as example<br>&nbsp; &nbsp;&nbsp; </span><span class="keyword">if(</span><span class="default">condition</span><span class="keyword">) { <br>&nbsp; &nbsp; &nbsp; &nbsp; return </span><span class="default">false</span><span class="keyword">;<br>&nbsp; &nbsp;&nbsp; }<br>&nbsp; }<br>&nbsp; finally {<br>&nbsp; &nbsp; </span><span class="comment">//close the sql connection, this will be executed even if the return is called.<br>&nbsp; </span><span class="keyword">}<br>}<br><br></span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="65203">  
  <a class="name">
  <strong class="user"><em>fjoggen at gmail dot com</em></strong></a><div class="date" title="2006-04-26 01:58"><strong>8 years ago</strong></div>
  <div class="text" id="Hcom65203">
<div class="phpcode"><code><span class="html">
This code will turn php errors into exceptions:<br><br><span class="default">&lt;?php<br></span><span class="keyword">function </span><span class="default">exceptions_error_handler</span><span class="keyword">(</span><span class="default">$severity</span><span class="keyword">, </span><span class="default">$message</span><span class="keyword">, </span><span class="default">$filename</span><span class="keyword">, </span><span class="default">$lineno</span><span class="keyword">) { <br>&nbsp; &nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$severity</span><span class="keyword">, </span><span class="default">$filename</span><span class="keyword">, </span><span class="default">$lineno</span><span class="keyword">); <br>}<br><br></span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">'exceptions_error_handler'</span><span class="keyword">);<br></span><span class="default">?&gt;<br></span><br>However since <span class="default">&lt;?php set_error_handler</span><span class="keyword">()</span><span class="default">?&gt;</span> doesn't work with fatal errors, you will not be able to throw them as Exceptions.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="105102">  
  <a class="name">
  <strong class="user"><em>alex dowgailenko [at] g mail . com</em></strong></a><div class="date" title="2011-07-27 12:20"><strong>3 years ago</strong></div>
  <div class="text" id="Hcom105102">
<div class="phpcode"><code><span class="html">
If you use the set_error_handler() to throw exceptions of errors, you may encounter issues with __autoload() functionality saying that your class doesn't exist and that's it.<br><br>If you do this:<br><br><span class="default">&lt;?php<br><br></span><span class="keyword">class </span><span class="default">MyException </span><span class="keyword">extends </span><span class="default">Exception<br></span><span class="keyword">{<br>}<br><br>class </span><span class="default">Tester<br></span><span class="keyword">{<br>&nbsp; &nbsp; public function </span><span class="default">foobar</span><span class="keyword">()<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; try<br>&nbsp; &nbsp; &nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">helloWorld</span><span class="keyword">();<br>&nbsp; &nbsp; &nbsp; &nbsp; } catch (</span><span class="default">MyException $e</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'Problem in foobar'</span><span class="keyword">,</span><span class="default">0</span><span class="keyword">,</span><span class="default">$e</span><span class="keyword">);<br>&nbsp; &nbsp; &nbsp; &nbsp; }<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; <br>&nbsp; &nbsp; protected function </span><span class="default">helloWorld</span><span class="keyword">()<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">MyException</span><span class="keyword">(</span><span class="string">'Problem in helloWorld()'</span><span class="keyword">);<br>&nbsp; &nbsp; }<br>}<br><br></span><span class="default">$tester </span><span class="keyword">= new </span><span class="default">Tester</span><span class="keyword">;<br>try<br>{<br>&nbsp; &nbsp; </span><span class="default">$tester</span><span class="keyword">-&gt;</span><span class="default">foobar</span><span class="keyword">();<br>} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; &nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">();<br>}<br></span><span class="default">?&gt;<br></span><br>The trace will only show $tester-&gt;foobar() and not the call made to $tester-&gt;helloWorld().<br><br>In other words, if you pass a previous exception to a new one, the previous exception's stack trace is taken into account in the new exception.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="106696">  
  <a class="name">
  <strong class="user"><em>Sawsan</em></strong></a><div class="date" title="2011-11-28 09:36"><strong>2 years ago</strong></div>
  <div class="text" id="Hcom106696">
<div class="phpcode"><code><span class="html">
the following is an example of a re-thrown exception and the using of getPrevious function:<br><br><span class="default">&lt;?php<br><br>$name </span><span class="keyword">= </span><span class="string">"Name"</span><span class="keyword">;<br><br></span><span class="comment">//check if the name contains only letters, and does not contain the word name<br><br></span><span class="keyword">try<br>&nbsp;&nbsp; {<br>&nbsp;&nbsp; try<br>&nbsp; &nbsp;&nbsp; {<br>&nbsp; &nbsp; &nbsp; if (</span><span class="default">preg_match</span><span class="keyword">(</span><span class="string">'/[^a-z]/i'</span><span class="keyword">, </span><span class="default">$name</span><span class="keyword">)) <br>&nbsp; &nbsp; &nbsp;&nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains character other than a-z A-Z"</span><span class="keyword">);<br>&nbsp; &nbsp; &nbsp;&nbsp; }&nbsp;&nbsp; <br>&nbsp; &nbsp; &nbsp;&nbsp; if(</span><span class="default">strpos</span><span class="keyword">(</span><span class="default">strtolower</span><span class="keyword">(</span><span class="default">$name</span><span class="keyword">), </span><span class="string">'name'</span><span class="keyword">) !== </span><span class="default">FALSE</span><span class="keyword">)<br>&nbsp; &nbsp; &nbsp;&nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains the word name"</span><span class="keyword">);<br>&nbsp; &nbsp; &nbsp;&nbsp; }<br>&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"The Name is valid"</span><span class="keyword">;<br>&nbsp; &nbsp;&nbsp; }<br>&nbsp;&nbsp; catch(</span><span class="default">Exception $e</span><span class="keyword">)<br>&nbsp; &nbsp;&nbsp; {<br>&nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"insert name again"</span><span class="keyword">,</span><span class="default">0</span><span class="keyword">,</span><span class="default">$e</span><span class="keyword">);<br>&nbsp; &nbsp;&nbsp; }<br>&nbsp;&nbsp; }<br> <br>catch (</span><span class="default">Exception $e</span><span class="keyword">)<br>&nbsp;&nbsp; {<br>&nbsp;&nbsp; if (</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">())<br>&nbsp;&nbsp; {<br>&nbsp; &nbsp; echo </span><span class="string">"The Previous Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br>&nbsp;&nbsp; }<br>&nbsp;&nbsp; echo </span><span class="string">"The Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br>&nbsp;&nbsp; }<br><br> </span><span class="default">?&gt;</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="72567">  
  <a class="name">
  <strong class="user"><em>jon at hackcraft dot net</em></strong></a><div class="date" title="2007-01-24 09:52"><strong>7 years ago</strong></div>
  <div class="text" id="Hcom72567">
<div class="phpcode"><code><span class="html">
Further to dexen at google dot me dot up with "use destructors to perform a cleanup in case of exception". The fact that PHP5 has destructors, exception handling, and predictable garbage collection (if there's a single reference in scope and the scope is left then the destructor is called immediately) allows for the use of the RAII idiom.<br><br><a rel="nofollow" target="_blank">http://en.wikipedia.org/wiki/Resource_Acquisition_Is_Initialization</a> and my own <a rel="nofollow" target="_blank">http://www.hackcraft.net/RAII/</a> describe this.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="78591">  
  <a class="name">
  <strong class="user"><em>hartym dot dont dot like dot spam at gmail dot com</em></strong></a><div class="date" title="2007-10-18 04:41"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom78591">
<div class="phpcode"><code><span class="html">
@serenity: of course you need to throw exception within the try block, catch will not watch fatal errors, nor less important errors but only exceptions that are instanceof the exception type you're giving. Of course by within the try block, i mean within every functions call happening in try block.<br><br>For example, to nicely handle old mysql errors, you can do something like this:<br><br><span class="default">&lt;?php<br></span><span class="keyword">try<br>{<br>&nbsp; </span><span class="default">$connection </span><span class="keyword">= </span><span class="default">mysql_connect</span><span class="keyword">(...);<br>&nbsp; if (</span><span class="default">$connection </span><span class="keyword">=== </span><span class="default">false</span><span class="keyword">)<br>&nbsp; {<br>&nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'Cannot connect do mysql'</span><span class="keyword">);<br>&nbsp; }<br><br>&nbsp;&nbsp; </span><span class="comment">/* ... do whatever you need with database, that may mail and throw exceptions too ... */<br><br>&nbsp;&nbsp; </span><span class="default">mysql_close</span><span class="keyword">(</span><span class="default">$connection</span><span class="keyword">);<br>}<br>catch (</span><span class="default">Exception $e</span><span class="keyword">)<br>{<br>&nbsp;&nbsp; </span><span class="comment">/* ... add logging stuff there if you need ... */<br><br>&nbsp; </span><span class="keyword">echo </span><span class="string">"This page cannot be displayed"</span><span class="keyword">;<br>}<br><br></span><span class="default">?&gt;<br></span><br>By doing so, you're aiming at the don't repeat yourself (D.R.Y) concept, by managing error handling at only one place for the whole.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="79577">  
  <a class="name">
  <strong class="user"><em>omnibus at omnibus dot edu dot pl</em></strong></a><div class="date" title="2007-12-04 03:11"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom79577">
<div class="phpcode"><code><span class="html">
Just to be more precise in what Frank found:<br>Catch the exceptions always in order from the bottom to the top of the Exception and subclasses class hierarchy. If you have class MyException extending Exception and class My2Exception extending MyException always catch My2Exception before MyException.<br><br>Hope this helps</span>
</code></div>
  </div>
 </div>
  <div class="note" id="81603">  
  <a class="name">
  <strong class="user"><em>chugadie dot geo at yahoo dot com</em></strong></a><div class="date" title="2008-03-05 10:40"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom81603">
<div class="phpcode"><code><span class="html">
@webmaster at asylum-et dot com<br><br>What Mo is describing is bug 44053 (<a rel="nofollow" target="_blank">http://bugs.php.net/bug.php?id=44053</a>) in which exceptions cannot be caught if you are using a custom error handler to catch warnings, notices, etc.</span>
</code></div>
  </div>
 </div></div>

 
</section>    </section><!-- layout-content -->
        


  </div><!-- layout -->
         
  

    
 <!-- External and third party libraries. -->
 







<a id="toTop" href="javascript:;"><span id="toTopHover"></span><img width="40" height="40" alt="To Top" src="../../images/to-top%402x.png"></a>



<!-- Mirrored from php.net/manual/en/language.exceptions.php by HTTrack Website Copier/3.x [XR&CO'2013], Thu, 28 Aug 2014 15:20:47 GMT -->


</body></html>